7.3/Dockerfile, Makefile
This has been already pushed to Docker hub so it's used in the [Free](https://github.com/mailpoet/mailpoet/pull/1871) and [Premium](https://github.com/mailpoet/mailpoet-premium/pull/197) pull requests.
=> Add image for PHP 7.3, simplified from previous images [MAILPOET-1864]

5.6.38/Dockerfile, 5.6/Dockerfile, 7.3/Dockerfile, Makefile
This is needed for testing the captcha.
P.S.: Could you please build and push the `5.6.38` container to the Hub? I have some issues building it (apache2 doesn't get installed for some reason).
=> Add FreeType support to 5.6 and 7.3 images [MAILPOET-2015]

Makefile, wp-5.3/Dockerfile
[MAILPOET-2544]
[MAILPOET-2544]: https://mailpoet.atlassian.net/browse/MAILPOET-2544
=> Add Dockerfile for Wordpress 5.3 [MAILPOET-2544]

7.0/Dockerfile, Makefile, wp-4.9/php7.0/Dockerfile
[MAILPOET-2570]
[MAILPOET-2663]
[MAILPOET-2570]: https://mailpoet.atlassian.net/browse/MAILPOET-2570
[MAILPOET-2663]: https://mailpoet.atlassian.net/browse/MAILPOET-2663
=> PHP 7.0 images [MAILPOET-2570] [MAILPOET-2663]

Makefile, wp-5.5/php7.4/Dockerfile
[MAILPOET-3096]
[MAILPOET-3096]: https://mailpoet.atlassian.net/browse/MAILPOET-3096
=> Add wp 5.5 image [MAILPOET-3096]

7.1/Dockerfile
[MAILPOET-3194]
[MAILPOET-3194]: https://mailpoet.atlassian.net/browse/MAILPOET-3194
=> Add FreeType support for PHP 7.1 [MAILPOET-3194]

7.2-cli/Dockerfile
[MAILPOET-3321]
[MAILPOET-3321]: https://mailpoet.atlassian.net/browse/MAILPOET-3321
=> Add unzip into docker image 7.2-cli [MAILPOET-3321]

7.4/Dockerfile
[MAILPOET-3280]
[MAILPOET-3280]: https://mailpoet.atlassian.net/browse/MAILPOET-3280
=> Update node.js in image for PHP 7.4 [MAILPOET-3280]

7.4-cli/Dockerfile, 8.0/Dockerfile, wp-5.6/php8.0/Dockerfile
[MAILPOET-3151]
[MAILPOET-3339]
[MAILPOET-3151]: https://mailpoet.atlassian.net/browse/MAILPOET-3151
[MAILPOET-3339]: https://mailpoet.atlassian.net/browse/MAILPOET-3339
=> New images for PHP 8.0 [MAILPOET-3151][MAILPOET-3339]

wp-5.3/php7.1/Dockerfile
[MAILPOET-3398]
[MAILPOET-3398]: https://mailpoet.atlassian.net/browse/MAILPOET-3398
=> Add Dockerfile with WP5.3 and PHP7.1 [MAILPOET-3398]

8.0/Dockerfile
[MAILPOET-3673]
[MAILPOET-3673]: https://mailpoet.atlassian.net/browse/MAILPOET-3673
=> Update node in 8.0 image to v16 (LTS) [MAILPOET-3673]

wp-5.8/php8.0/Dockerfile
[MAILPOET-3967]
[MAILPOET-3967]: https://mailpoet.atlassian.net/browse/MAILPOET-3967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Dockerfile with WP 5.8 for PHP 8.0 [MAILPOET-3967]

wp-5.9/php8.0/Dockerfile, wp-5.9/php8.1/Dockerfile
Images are published here:
- https://hub.docker.com/layers/mailpoet/wordpress/wp-5.9_php8.0_20220127.1/images/sha256-2e893ecd36a9d2571dc3a29757bcda64ed5156fea185942bbf6032fad5d97fc9?context=explore
- https://hub.docker.com/layers/mailpoet/wordpress/wp-5.9_php8.1_20220130.1/images/sha256-79e4356c7e48164438cb33150b041e2f824f2812be4c42d53aea7eed388e6e87?context=explore
[MAILPOET-4014]
[MAILPOET-4014]: https://mailpoet.atlassian.net/browse/MAILPOET-4014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Dockerfile images for WP5.9

README.md
Update readme to include the build command for multiplatform images
=> Build multi platform images

7.2/Dockerfile, 8.1/Dockerfile
[MAILPOET-4015]
[MAILPOET-4015]: https://mailpoet.atlassian.net/browse/MAILPOET-4015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Docker file with PHP 8.1 [MAILPOET-4015]

7.4-cli/Dockerfile, 8.0-cli/Dockerfile
- Enables image generation for Captcha
- Enables catching emails in Mailhog using MSMTP
- Adds Xdebug
[MAILPOET-4251]
[MAILPOET-4251]: https://mailpoet.atlassian.net/browse/MAILPOET-4251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adjust used Docker container to run integration tests [MAILPOET-4251]

7.2-cli/Dockerfile
[MAILPOET-4251]
[MAILPOET-4251]: https://mailpoet.atlassian.net/browse/MAILPOET-4251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Xdebug, jpeg generation support and msmtp to 7.2-cli

wp-6.0/php8.0/Dockerfile, wp-6.0/php8.1/Dockerfile
Images are published here:
https://hub.docker.com/r/mailpoet/wordpress/tags?page=1&name=wp-6.0
This PR was created following the instructions from https://mailpoetp2.wordpress.com/team-handbook/engineering-process/qa-processes/project-mailpoet-3-plugin/how-to-update-the-acceptance-tests-environment/
[MAILPOET-4297]
[MAILPOET-4297]: https://mailpoet.atlassian.net/browse/MAILPOET-4297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Dockerfile images for WP 6.0

7.4/Dockerfile, 8.1/Dockerfile
For context, see: https://github.com/mailpoet/mailpoet/pull/4262
The updated images were already pushed as `mailpoet/wordpress:8.1_20220718.1` and `mailpoet/wordpress:7.4_20220718.1`.
[MAILPOET-4485]
[MAILPOET-4485]: https://mailpoet.atlassian.net/browse/MAILPOET-4485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Node.js to v17, enable Corepack [MAILPOET-4485]

wp-6.1/php8.0/Dockerfile, wp-6.1/php8.1/Dockerfile
https://github.com/mailpoet/mailpoet/pull/4551
[MAILPOET-4841]
[MAILPOET-4841]: https://mailpoet.atlassian.net/browse/MAILPOET-4841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add new images with the latest WP version 6.1 [MAILPOET-4841]

wp-5.9/php7.3/Dockerfile
[MAILPOET-4893]
[MAILPOET-4893]: https://mailpoet.atlassian.net/browse/MAILPOET-4893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Dockerfile for WP 5.9 PHP 7.3 image

wp-6.0/php7.4/Dockerfile, wp-6.2/php8.0/Dockerfile, wp-6.2/php8.1/Dockerfile, wp-6.2/php8.2/Dockerfile
This PR adds the config files for WP 6.2 images.
[MAILPOET-5075]
[MAILPOET-5075]: https://mailpoet.atlassian.net/browse/MAILPOET-5075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WP 6.2 images

wp-6.3/php8.0/Dockerfile, wp-6.3/php8.1/Dockerfile, wp-6.3/php8.2/Dockerfile
This PR adds the config files for WP 6.3 images.
Published here: https://hub.docker.com/repository/docker/mailpoet/wordpress/tags?page=1&ordering=last_updated&name=wp-6.3
[MAILPOET-5527]
[MAILPOET-5527]: https://mailpoet.atlassian.net/browse/MAILPOET-5527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add WP 6.3 Images

wp-6.4/php8.0/Dockerfile, wp-6.4/php8.1/Dockerfile, wp-6.4/php8.2/Dockerfile
This is part of [MAILPOET-5713]. The image seems to be fine but the acceptance tests are failing (looks like they are failing because of changes in the WP default theme) and that is why I haven't created yet a PR on the free plugin repository.
[MAILPOET-5713]: https://mailpoet.atlassian.net/browse/MAILPOET-5713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create Docker image for WP 6.4

8.3-cli/Dockerfile, 8.3/Dockerfile
[MAILPOET-6297]
[MAILPOET-6297]: https://mailpoet.atlassian.net/browse/MAILPOET-6297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add PHP 8.3 images [MAILPOET-6297]
